import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import LayoutScript from "@/components/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutScript />
        {children}
      </body>
    </html>
  );
}
